service: sls-rest-api
frameworkVersion: "3.1.0"

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom:defaultStage}
  region: ap-northeast-1
  profile: sls-test
  deploymentBucket:
    name: furu-sls-deployment-bucket-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TODO_TABLE}
  environment:
    DYNAMODB_TODO_TABLE: ${self:service}-dynamodb-todo-table-${opt:stage, self:provider.stage}

functions:
  create-todo:
    handler: handler.createTodo
    events:
      - http:
          path: /api/v1/todo
          method: post
  get-all-todo:
    handler: handler.getAllTodo
    events:
      - http:
          path: /api/v1/todo
          method: get

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TODO_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  defaultStage: local
  prune:
    automatic: true
    number: 3
